# Generated by Django 4.0.4 on 2022-06-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_review_stars_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
